import type { Config } from "tailwindcss";

export default {
  // Tailwind가 클래스를 검색할 파일 경로들 지정
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/modals/**/*.{js,ts,jsx,tsx,mdx}",
    //===============================================//
    // app\layout.tsx -> <PrimeReactProvider value={{ unstyled: false, ...}}>
    // PrimeReactProvider로 전역 적용 할시 unstyled가 false 일때 적용될 테마 파일//
    // "./node_modules/primereact/**/*.{js,ts,jsx,tsx}",
    "./primereact.config.ts"
    //===============================================//
  ],
  // 동적/조건부 Tailwind 클래스 강제 포함 시 사용
  safelist: [
    "px-1", "px-2", "px-4", "px-6", "px-8", "px-10", "px-12",
    "py-1", "py-2", "py-4", "py-6", "py-8", "py-10", "py-12",
    "pt-1", "pt-2", "pt-4", "pt-6", "pt-8", "pt-10", "pt-12",
    "pb-1", "pb-2", "pb-4", "pb-6", "pb-8", "pb-10", "pb-12",
    "pl-1", "pl-2", "pl-4", "pl-6", "pl-8", "pl-10", "pl-12",
    "pr-1", "pr-2", "pr-4", "pr-6", "pr-8", "pr-10", "pr-12",
    "p-1", "p-2", "p-4", "p-6", "p-8", "p-10", "p-12",
    // col
    "col-span-1", "col-span-2", "col-span-3", "col-span-4", "col-span-5", "col-span-6",
    "col-span-7", "col-span-8", "col-span-9", "col-span-10", "col-span-11", "col-span-12",
    // sm
    "sm:col-span-1", "sm:col-span-2", "sm:col-span-3", "sm:col-span-4", "sm:col-span-5", "sm:col-span-6",
    "sm:col-span-7", "sm:col-span-8", "sm:col-span-9", "sm:col-span-10", "sm:col-span-11", "sm:col-span-12",
    // md
    "md:col-span-1", "md:col-span-2", "md:col-span-3", "md:col-span-4", "md:col-span-5", "md:col-span-6",
    "md:col-span-7", "md:col-span-8", "md:col-span-9", "md:col-span-10", "md:col-span-11", "md:col-span-12",
    // lg
    "lg:col-span-1", "lg:col-span-2", "lg:col-span-3", "lg:col-span-4", "lg:col-span-5", "lg:col-span-6",
    "lg:col-span-7", "lg:col-span-8", "lg:col-span-9", "lg:col-span-10", "lg:col-span-11", "lg:col-span-12",
    // xl
    "xl:col-span-1", "xl:col-span-2", "xl:col-span-3", "xl:col-span-4", "xl:col-span-5", "xl:col-span-6",
    "xl:col-span-7", "xl:col-span-8", "xl:col-span-9", "xl:col-span-10", "xl:col-span-11", "xl:col-span-12",
    // 2xl
    "2xl:col-span-1", "2xl:col-span-2", "2xl:col-span-3", "2xl:col-span-4", "2xl:col-span-5", "2xl:col-span-6",
    "2xl:col-span-7", "2xl:col-span-8", "2xl:col-span-9", "2xl:col-span-10", "2xl:col-span-11", "2xl:col-span-12",

    "text-left", "text-right", "text-center", "truncate"

  ],
  // 프로젝트의 디자인 토큰 확장 (색상, 폰트 등)
  theme: {
    extend: {
      screens: { // 변경시 styleConstants.ScreenBreakpoints 함께 수정
        sm: '480px',
        md: '768px',
        lg: '1200px',
        xl: '1440px',
        '2xl': '1920px',
      },
      colors: {
        primary: "var(--primary)",
        primaryLowest: "var(--primary-lowest)",
        primaryLower: "var(--primary-lower)",
        primaryLow: "var(--primary-low)",
        primaryMid: "var(--primary-mid)",
        primaryHigh: "var(--primary-high)",
        primaryHigher: "var(--primary-higher)",
        primaryHighest: "var(--primary-highest)",
        onPrimary: "var(--on-primary)",
        onPrimaryLowest: "var(--on-primary-lowest)",
        onPrimaryLower: "var(--on-primary-lower)",
        onPrimaryLow: "var(--on-primary-low)",
        onPrimaryMid: "var(--on-primary-mid)",
        onPrimaryHigh: "var(--on-primary-high)",
        onPrimaryHigher: "var(--on-primary-higher)",
        onPrimaryHighest: "var(--on-primary-highest)",
        primaryContainer: "var(--primary-container)",
        primaryContainerLowest: "var(--primary-container-lowest)",
        primaryContainerLower: "var(--primary-container-lower)",
        primaryContainerLow: "var(--primary-container-low)",
        primaryContainerMid: "var(--primary-container-mid)",
        primaryContainerHigh: "var(--primary-container-high)",
        primaryContainerHigher: "var(--primary-container-higher)",
        primaryContainerHighest: "var(--primary-container-highest)",
        onPrimaryContainer: "var(--on-primary-container)",
        onPrimaryContainerLowest: "var(--on-primary-container-lowest)",
        onPrimaryContainerLower: "var(--on-primary-container-lower)",
        onPrimaryContainerLow: "var(--on-primary-container-low)",
        onPrimaryContainerMid: "var(--on-primary-container-mid)",
        onPrimaryContainerHigh: "var(--on-primary-container-high)",
        onPrimaryContainerHigher: "var(--on-primary-container-higher)",
        onPrimaryContainerHighest: "var(--on-primary-container-highest)",
        secondary: "var(--secondary)",
        secondaryLowest: "var(--secondary-lowest)",
        secondaryLower: "var(--secondary-lower)",
        secondaryLow: "var(--secondary-low)",
        secondaryMid: "var(--secondary-mid)",
        secondaryHigh: "var(--secondary-high)",
        secondaryHigher: "var(--secondary-higher)",
        secondaryHighest: "var(--secondary-highest)",
        onSecondary: "var(--on-secondary)",
        onSecondaryLowest: "var(--on-secondary-lowest)",
        onSecondaryLower: "var(--on-secondary-lower)",
        onSecondaryLow: "var(--on-secondary-low)",
        onSecondaryMid: "var(--on-secondary-mid)",
        onSecondaryHigh: "var(--on-secondary-high)",
        onSecondaryHigher: "var(--on-secondary-higher)",
        onSecondaryHighest: "var(--on-secondary-highest)",
        secondaryContainer: "var(--secondary-container)",
        secondaryContainerLowest: "var(--secondary-container-lowest)",
        secondaryContainerLower: "var(--secondary-container-lower)",
        secondaryContainerLow: "var(--secondary-container-low)",
        secondaryContainerMid: "var(--secondary-container-mid)",
        secondaryContainerHigh: "var(--secondary-container-high)",
        secondaryContainerHigher: "var(--secondary-container-higher)",
        secondaryContainerHighest: "var(--secondary-container-highest)",
        onSecondaryContainer: "var(--on-secondary-container)",
        onSecondaryContainerLowest: "var(--on-secondary-container-lowest)",
        onSecondaryContainerLower: "var(--on-secondary-container-lower)",
        onSecondaryContainerLow: "var(--on-secondary-container-low)",
        onSecondaryContainerMid: "var(--on-secondary-container-mid)",
        onSecondaryContainerHigh: "var(--on-secondary-container-high)",
        onSecondaryContainerHigher: "var(--on-secondary-container-higher)",
        onSecondaryContainerHighest: "var(--on-secondary-container-highest)",
        surface: "var(--surface)",
        surfaceLowest: "var(--surface-lowest)",
        surfaceLower: "var(--surface-lower)",
        surfaceLow: "var(--surface-low)",
        surfaceMid: "var(--surface-mid)",
        surfaceHigh: "var(--surface-high)",
        surfaceHigher: "var(--surface-higher)",
        surfaceHighest: "var(--surface-highest)",
        onSurface: "var(--on-surface)",
        onSurfaceLowest: "var(--on-surface-lowest)",
        onSurfaceLower: "var(--on-surface-lower)",
        onSurfaceLow: "var(--on-surface-low)",
        onSurfaceMid: "var(--on-surface-mid)",
        onSurfaceHigh: "var(--on-surface-high)",
        onSurfaceHigher: "var(--on-surface-higher)",
        onSurfaceHighest: "var(--on-surface-highest)",
        surfaceContainer: "var(--surface-container)",
        surfaceContainerLowest: "var(--surface-container-lowest)",
        surfaceContainerLower: "var(--surface-container-lower)",
        surfaceContainerLow: "var(--surface-container-low)",
        surfaceContainerMid: "var(--surface-container-mid)",
        surfaceContainerHigh: "var(--surface-container-high)",
        surfaceContainerHigher: "var(--surface-container-higher)",
        surfaceContainerHighest: "var(--surface-container-highest)",
        onSurfaceContainer: "var(--on-surface-container)",
        onSurfaceContainerLowest: "var(--on-surface-container-lowest)",
        onSurfaceContainerLower: "var(--on-surface-container-lower)",
        onSurfaceContainerLow: "var(--on-surface-container-low)",
        onSurfaceContainerMid: "var(--on-surface-container-mid)",
        onSurfaceContainerHigh: "var(--on-surface-container-high)",
        onSurfaceContainerHigher: "var(--on-surface-container-higher)",
        onSurfaceContainerHighest: "var(--on-surface-container-highest)",
        outline: "var(--outline)",
        outlineLowest: "var(--outline-lowest)",
        outlineLower: "var(--outline-lower)",
        outlineLow: "var(--outline-low)",
        outlineMid: "var(--outline-mid)",
        outlineHigh: "var(--outline-high)",
        outlineHigher: "var(--outline-higher)",
        outlineHighest: "var(--outline-highest)",
        transparency: "var(--transparency)",
        transparencyLower: "var(--transparency-lower)",
        transparencyLow: "var(--transparency-low)",
        transparencyMid: "var(--transparency-mid)",
        transparencyHigh: "var(--transparency-high)",
        transparencyHigher: "var(--transparency-higher)",
        red: "var(--red)",
        redLow: "var(--red-low)",
        redHigh: "var(--red-high)",
        onRed: "var(--on-red)",
        onRedLow: "var(--on-red-low)",
        onRedHigh: "var(--on-red-high)",
        redContainer: "var(--red-container)",
        redContainerLow: "var(--red-container-low)",
        redContainerHigh: "var(--red-container-high)",
        onRedContainer: "var(--on-red-container)",
        onRedContainerLow: "var(--on-red-container-low)",
        onRedContainerHigh: "var(--on-red-container-high)",
        orange: "var(--orange)",
        orangeLow: "var(--orange-low)",
        orangeHigh: "var(--orange-high)",
        onOrange: "var(--on-orange)",
        onOrangeLow: "var(--on-orange-low)",
        onOrangeHigh: "var(--on-orange-high)",
        orangeContainer: "var(--orange-container)",
        orangeContainerLow: "var(--orange-container-low)",
        orangeContainerHigh: "var(--orange-container-high)",
        onOrangeContainer: "var(--on-orange-container)",
        onOrangeContainerLow: "var(--on-orange-container-low)",
        onOrangeContainerHigh: "var(--on-orange-container-high)",
        yellow: "var(--yellow)",
        yellowLow: "var(--yellow-low)",
        yellowHigh: "var(--yellow-high)",
        onYellow: "var(--on-yellow)",
        onYellowLow: "var(--on-yellow-low)",
        onYellowHigh: "var(--on-yellow-high)",
        yellowContainer: "var(--yellow-container)",
        yellowContainerLow: "var(--yellow-container-low)",
        yellowContainerHigh: "var(--yellow-container-high)",
        onYellowContainer: "var(--on-yellow-container)",
        onYellowContainerLow: "var(--on-yellow-container-low)",
        onYellowContainerHigh: "var(--on-yellow-container-high)",
        green: "var(--green)",
        greenLow: "var(--green-low)",
        greenHigh: "var(--green-high)",
        onGreen: "var(--on-green)",
        onGreenLow: "var(--on-green-low)",
        onGreenHigh: "var(--on-green-high)",
        greenContainer: "var(--green-container)",
        greenContainerLow: "var(--green-container-low)",
        greenContainerHigh: "var(--green-container-high)",
        onGreenContainer: "var(--on-green-container)",
        onGreenContainerLow: "var(--on-green-container-low)",
        onGreenContainerHigh: "var(--on-green-container-high)",
        teal: "var(--teal)",
        tealLow: "var(--teal-low)",
        tealHigh: "var(--teal-high)",
        onTeal: "var(--on-teal)",
        onTealLow: "var(--on-teal-low)",
        onTealHigh: "var(--on-teal-high)",
        tealContainer: "var(--teal-container)",
        tealContainerLow: "var(--teal-container-low)",
        tealContainerHigh: "var(--teal-container-high)",
        onTealContainer: "var(--on-teal-container)",
        onTealContainerLow: "var(--on-teal-container-low)",
        onTealContainerHigh: "var(--on-teal-container-high)",
        cyan: "var(--cyan)",
        cyanLow: "var(--cyan-low)",
        cyanHigh: "var(--cyan-high)",
        onCyan: "var(--on-cyan)",
        onCyanLow: "var(--on-cyan-low)",
        onCyanHigh: "var(--on-cyan-high)",
        cyanContainer: "var(--cyan-container)",
        cyanContainerLow: "var(--cyan-container-low)",
        cyanContainerHigh: "var(--cyan-container-high)",
        onCyanContainer: "var(--on-cyan-container)",
        onCyanContainerLow: "var(--on-cyan-container-low)",
        onCyanContainerHigh: "var(--on-cyan-container-high)",
        blue: "var(--blue)",
        blueLow: "var(--blue-low)",
        blueHigh: "var(--blue-high)",
        onBlue: "var(--on-blue)",
        onBlueLow: "var(--on-blue-low)",
        onBlueHigh: "var(--on-blue-high)",
        blueContainer: "var(--blue-container)",
        blueContainerLow: "var(--blue-container-low)",
        blueContainerHigh: "var(--blue-container-high)",
        onBlueContainer: "var(--on-blue-container)",
        onBlueContainerLow: "var(--on-blue-container-low)",
        onBlueContainerHigh: "var(--on-blue-container-high)",
        purple: "var(--purple)",
        purpleLow: "var(--purple-low)",
        purpleHigh: "var(--purple-high)",
        onPurple: "var(--on-purple)",
        onPurpleLow: "var(--on-purple-low)",
        onPurpleHigh: "var(--on-purple-high)",
        purpleContainer: "var(--purple-container)",
        purpleContainerLow: "var(--purple-container-low)",
        purpleContainerHigh: "var(--purple-container-high)",
        onPurpleContainer: "var(--on-purple-container)",
        onPurpleContainerLow: "var(--on-purple-container-low)",
        onPurpleContainerHigh: "var(--on-purple-container-high)",
        violet: "var(--violet)",
        violetLow: "var(--violet-low)",
        violetHigh: "var(--violet-high)",
        onViolet: "var(--on-violet)",
        onVioletLow: "var(--on-violet-low)",
        onVioletHigh: "var(--on-violet-high)",
        violetContainer: "var(--violet-container)",
        violetContainerLow: "var(--violet-container-low)",
        violetContainerHigh: "var(--violet-container-high)",
        onVioletContainer: "var(--on-violet-container)",
        onVioletContainerLow: "var(--on-violet-container-low)",
        onVioletContainerHigh: "var(--on-violet-container-high)",
        opacity0: "var(--opacity-0)",
        opacityLight10: "var(--opacity-light-10)",
        opacityLight20: "var(--opacity-light-20)",
        opacityLight30: "var(--opacity-light-30)",
        opacityLight40: "var(--opacity-light-40)",
        opacityLight50: "var(--opacity-light-50)",
        opacityLight60: "var(--opacity-light-60)",
        opacityLight70: "var(--opacity-light-70)",
        opacityLight80: "var(--opacity-light-80)",
        opacityDark10: "var(--opacity-dark-10)",
        opacityDark20: "var(--opacity-dark-20)",
        opacityDark30: "var(--opacity-dark-30)",
        opacityDark40: "var(--opacity-dark-40)",
        opacityDark50: "var(--opacity-dark-50)",
        opacityDark60: "var(--opacity-dark-60)",
        opacityDark70: "var(--opacity-dark-70)",
        opacityDark80: "var(--opacity-dark-80)",
        variantBackdrop: "var(--variant-backdrop)"
      },
      boxShadow: {
        "gs1": "0px 1px 10px 1px rgba(0, 0, 0, 0.03)",
        "gs2": "0px 2px 14px 2px rgba(0, 0, 0, 0.06)",
        "gs3": "0px 4px 17px 3px rgba(0, 0, 0, 0.09)",
        "gs4": "0px 6px 24px 4px rgba(0, 0, 0, 0.12)",
        "gs5": "0px 8px 30px 6px rgba(0, 0, 0, 0.15)",
        "bs04": "0px 2px 4px 0px rgba(0, 0, 0, 0.04), 0px 8px 16px 0px rgba(0, 0, 0, 0.09)"
      },
      fontSize: {
        "headline-md": ["28px", { fontWeight: "700" }],
        "headline-sm": ["24px", { fontWeight: "700" }],

        "title-lg": ["20px", { fontWeight: "700" }],
        "title-md": ["18px", { fontWeight: "700" }],
        "title-sm": ["16px", { fontWeight: "700" }],
        "title-xs": ["14px", { fontWeight: "700" }],

        "label-xl": ["16px", { fontWeight: "500" }],
        "label-lg": ["15px", { fontWeight: "500" }],
        "label-md": ["14px", { fontWeight: "500" }],
        "label-sm": ["13px", { fontWeight: "500" }],
        "label-xs": ["12px", { fontWeight: "500" }],

        "body-bold-2xl": ["44px", { fontWeight: "700" }],
        "body-bold-xl": ["30px", { fontWeight: "700" }],
        "body-bold-lg": ["26px", { fontWeight: "700" }],
        "body-bold-md": ["24px", { fontWeight: "700" }],
        "body-bold-sm": ["18px", { fontWeight: "700" }],
        "body-bold-xs": ["15px", { fontWeight: "700" }],
        "body-bold-xxs": ["14px", { fontWeight: "700" }],

        "body-xl": ["16px", { fontWeight: "400" }],
        "body-lg": ["15px", { fontWeight: "400" }],
        "body-md": ["14px", { fontWeight: "400" }],
        "body-sm": ["13px", { fontWeight: "400" }],
        "body-xs": ["12px", { fontWeight: "400" }],

        "caption-lg": ["12px", { fontWeight: "400" }],
        "caption-md": ["11px", { fontWeight: "400" }],
        "caption-sm": ["10px", { fontWeight: "400" }]
      },
      spacing: {
        xxs: "2px",
        xs: "4px",
        sm: "8px",
        md: "16px",
        lg: "24px",
        xl: "32px",
        "2xl": "48px",
        "3xl": "64px"
      },
      gap: {
        xxs: "2px",
        xs: "4px",
        sm: "8px",
        md: "16px",
        lg: "24px",
        xl: "32px",
        "2xl": "48px",
        "3xl": "64px"
      },
      borderRadius: {
        xxs: "2px",
        xs: "3px",
        sm: "4px",
        md: "6px",
        lg: "8px",
        mxl: "12px",
      },
      backgroundImage: {
        'login-bg': "url('/assets/images/login-bg.png')",
        'rainbow':
          "linear-gradient(90deg, #22BA4F 0%, #FFD500 40.87%, #FAA52E 64.42%, #FF334B 81.25%, #924BFF 100%)",
      }
    }
  },
  plugins: []
} satisfies Config;
